#!/usr/bin/env sh

# === YabaiRC ===
# Official Docs: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc
# Jesse Skelton's Notion Docs: https://www.notion.so/Yabai-8da3b829872d432fac43181b7ff628fc

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                              layout bsp

yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_topmost               off

yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
#
# center mouse on window with focus
yabai -m config mouse_follows_focus          on

# modifier for clicking and dragging with mouse
# yabai -m config mouse_modifier              alt

# set modifier + left-click drag to move window
# yabai -m config mouse_action1               move

# set modifier + right-click drag to resize window
# yabai -m config mouse_action2               resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action           swap

yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# float system preferences. Most of these just diable Yabai form resizing them.
# Small Windows
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Raycast$" manage=off 
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Logi Options$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^HotKey$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Docker Desktop$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Finder$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Home$" manage=off grid=4:4:1:1:2:2

# Big Windows 
## EDC
yabai -m rule --add app="^Calendar$" layer=above manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Things$" layer=above manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^1Password 7$" layer=above manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Spotify$" layer=above manage=off grid=8:8:1:1:6:6

## Dev
yabai -m rule --add app="^Insomnia$" layer=above manage=off grid=8:8:1:1:6:6
# yabai -m rule --add app="^Sketch$" layer=above manage=off grid=8:8:1:1:6:6

# regex that matches JetBrains apps
apps='^(IntelliJ IDEA|WebStorm|CLion)$'

# float all JetBrains apps
yabai -m rule --add app="${apps}" manage=off

# add a signal that floats a window created by these apps when it's the only window
yabai -m signal --add event=window_created app="${apps}" action="$HOME/.scripts/yabai-jetbrains-fix.sh"

yabai -m signal --add event=window_created action="yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".resizable == 0 and .floating == 0" && yabai -m window $YABAI_WINDOW_ID --toggle float"

#Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
# limelight &>/dev/null &
