session: config

root: ~/.config

windows:
  - name: config
    layout: main-horizontal
    commands:
      - nvim .
  - name: nvim
    layout: main-horizontal
    commands:
      - nvim ./nvim
  - name: tmux
    layout: main-horizontal
    commands:
      - nvim ./tmux/tmux.conf
  - name: smug
    layout: main-horizontal
    commands:
      - nvim ./smug
