session: config

root: ~/.config

windows:
  - name: lazyvin
    commands:
      - cd nvim
      - nvim .
  - name: vin
    commands:
      - cd vin
      - nvim .
    panes:
      - type: vertical
        commands:
          - cd $HOME/.local/share/nvim/lazy/LazyVim
          - nvim .
  - name: term
    commands:
      - nvim -O ./wezterm/wezterm.lua ./tmux/tmux.conf
  - name: smug
    commands:
      - cd smug
      - nvim .
