session: config

root: ~/.config

windows:
  - name: term
    layout: main-horizontal
  - name: config
    layout: main-horizontal
    commands:
      - $EDITOR .
  - name: nvim
    layout: main-horizontal
    commands:
      - $EDITOR ./nvim
  - name: kitty
    layout: main-horizontal
    commands:
      - $EDITOR ./kitty/kitty.conf
  - name: tmux
    layout: main-horizontal
    commands:
      - $EDITOR ./tmux/tmux.conf
  - name: smug
    layout: main-horizontal
    commands:
      - $EDITOR ./smug
