session: config

root: ~/.config

windows:
  - name: term
    layout: main-horizontal
  - name: config
    layout: main-horizontal
    commands:
      - lvim .
  - name: lvim
    layout: main-horizontal
    commands:
      - lvim ./lvim
  - name: kitty
    layout: main-horizontal
    commands:
      - lvim ./kitty/kitty.conf
  - name: tmux
    layout: main-horizontal
    commands:
      - lvim ./tmux/tmux.conf
  - name: smug
    layout: main-horizontal
    commands:
      - lvim ./smug
