session: config

root: ~/.config

windows:
  - name: config
    layout: main-horizontal
    commands:
      - nvim .
  - name: lazyvin/vin
    commands:
      - cd nvim
      - clear
      - nvim .
    panes:
      - type: horizontal
        commands:
          - cd vin
          - clear
          - nvim .
  - name: LazyVim
    commands:
      - cd ~/Documents/dev/repos/other/LazyVim
      - clear
      - nvim .
  - name: tmux
    layout: main-horizontal
    commands:
      - cd tmux
      - nvim .
  - name: smug
    layout: main-horizontal
    commands:
      - cd smug
      - nvim .
