session: config

root: ~/.config

windows:
  - name: config
    layout: main-horizontal
    commands:
      - lvim .
  - name: lvim
    layout: main-horizontal
    commands:
      - lvim ./lvim
  - name: tmux
    layout: main-horizontal
    commands:
      - lvim ./tmux/tmux.conf
  - name: smug
    layout: main-horizontal
    commands:
      - lvim ./smug
