session: config

root: ~/.config

windows:
  - name: config
    layout: main-horizontal
    commands:
      - nvim .
  - name: lazyvin
    commands:
      - cd nvim
      - clear
      - nvim .
  - name: LazyVim
    commands:
      - cd ~/Documents/dev/repos/other/LazyVim
      - clear
      - nvim .
