session: config

root: ~/.config

windows:
  - name: config
    layout: main-horizontal
    commands:
      - nvim .
  - name: nvim
    root: nvim
    layout: main-horizontal
    commands:
      - nvim .
  - name: tmux
    layout: main-horizontal
    commands:
      - cd tmux
      - nvim .
  - name: smug
    layout: main-horizontal
    commands:
      - cd smug
      - nvim .
