[colors]
foreground = "#e0ddd1"
background = "#212523"
cursor_bg = "#e0ddd1"
cursor_border = "#e0ddd1"
cursor_fg = "#212523"
selection_bg = "#394740"
selection_fg = "#e0ddd1"
split = "#85ad9f"
compose_cursor = "#c6b3da"
scrollbar_thumb = "#51635a"

ansi = ["#212523", "#ba6e5f", "#8ac090", "#d6d0c2", "#99b9e6", "#c6b3da", "#85ad9f", "#82978c"]
brights = ["#677e72", "#ba6e5f", "#8ac090", "#d6d0c2", "#99b9e6", "#c6b3da", "#85ad9f", "#e0ddd1"]

[colors.tab_bar]
inactive_tab_edge = "#1d201f"
background = "#212523"

[colors.tab_bar.active_tab]
fg_color = "#1d201f"
bg_color = "#99b9e6"

[colors.tab_bar.inactive_tab]
fg_color = "#51635a"
bg_color = "#394740"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#99b9e6"
bg_color = "#394740"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#99b9e6"
bg_color = "#212523"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#99b9e6"
bg_color = "#212523"

[metadata]
aliases = []
author = "Black Atom Industries"
name = "Black Atom - Terra Spring Night"
