[colors]
foreground = "#d6d0c2"
background = "#212523"
cursor_bg = "#8ac090"
cursor_border = "#8ac090"
cursor_fg = "#212523"
selection_bg = "#394740"
selection_fg = "#d6d0c2"
split = "#8ac090"
compose_cursor = "#c6b3da"
scrollbar_thumb = "#51635a"

ansi = [
  "#313634", # black
  "#b95847", # red
  "#6a9f60", # green
  "#e89a61", # yellow
  "#899ddc", # blue
  "#d5a9c3", # magenta
  "#679980", # cyan
  "#c3b8a4", # gray
]

brights = [
  "#677e72", # black
  "#ba6e5f", # red
  "#8ac090", # green
  "#d1a762", # yellow
  "#99b9e6", # blue
  "#c6b3da", # magenta
  "#85ad9f", # cyan
  "#d6d0c2", # gray
]

[colors.tab_bar]
inactive_tab_edge = "#1d201f"
background = "#212523"

[colors.tab_bar.active_tab]
fg_color = "#1d201f"
bg_color = "#99b9e6"

[colors.tab_bar.inactive_tab]
fg_color = "#51635a"
bg_color = "#394740"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#99b9e6"
bg_color = "#394740"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#99b9e6"
bg_color = "#212523"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#99b9e6"
bg_color = "#212523"

[metadata]
author = "Black Atom Industries"
name = "Black Atom - Terra Spring Night"
