[colors]
foreground = "#d0e0d8"
background = "#181b1a"
cursor_bg = "#88DCB2"
cursor_border = "#88DCB2"
cursor_fg = "#181b1a"
selection_bg = "#3e4441"
selection_fg = "#d0e0d8"
split = "#88DCB2"
compose_cursor = "#b7aded"
scrollbar_thumb = "#565f59"

ansi = [
  "#181b1a", # black
  "#9891d6", # dark_red
  "#4a9a64", # dark_green
  "#9fafa7", # dark_yellow
  "#79857f", # dark_blue
  "#a498e9", # dark_magenta
  "#61d098", # dark_cyan
  "#abbbb3", # light_gray
]

brights = [
  "#3e4441", # gray
  "#a6a1df", # red
  "#64b47e", # green
  "#c4d4cc", # yellow
  "#abbbb3", # blue
  "#b7aded", # magenta
  "#88DCB2", # cyan
  "#c4d4cc", # white
]

[colors.tab_bar]
inactive_tab_edge = "#141515"
background = "#181b1a"

[colors.tab_bar.active_tab]
fg_color = "#141515"
bg_color = "#abbbb3"

[colors.tab_bar.inactive_tab]
fg_color = "#565f59"
bg_color = "#3e4441"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#abbbb3"
bg_color = "#3e4441"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#abbbb3"
bg_color = "#181b1a"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#abbbb3"
bg_color = "#181b1a"

[metadata]
aliases = []
author = "Black Atom Industries"
name = "Black Atom - Operations"
