[colors]
foreground = "#d0e0d8"
background = "#0e1110"
cursor_bg = "#88DCB2"
cursor_border = "#88DCB2"
cursor_fg = "#0e1110"
selection_bg = "#3e4441"
selection_fg = "#d0e0d8"
split = "#88DCB2"
compose_cursor = "#b7aded"
scrollbar_thumb = "#565f59"

ansi = [
  "#0e1110", # black
  "#9891d6", # dark_red
  "#8ebd77", # dark_green
  "#9fafa7", # dark_yellow
  "#79857f", # dark_blue
  "#a498e9", # dark_magenta
  "#61d098", # dark_cyan
  "#79857f", # light_gray
]
brights = [
  "#566f62", # gray
  "#a6a1df", # red
  "#99cf7e", # green
  "#99cf7e", # yellow
  "#abbbb3", # blue
  "#b7aded", # magenta
  "#88DCB2", # cyan
  "#c4d4cc", # white
]

[colors.tab_bar]
inactive_tab_edge = "#040505"
background = "#0e1110"

[colors.tab_bar.active_tab]
fg_color = "#040505"
bg_color = "#abbbb3"

[colors.tab_bar.inactive_tab]
fg_color = "#565f59"
bg_color = "#3e4441"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#abbbb3"
bg_color = "#3e4441"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#abbbb3"
bg_color = "#0e1110"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#abbbb3"
bg_color = "#0e1110"

[metadata]
author = "Black Atom Industries"
name = "Black Atom - Engineering"
