[colors]
foreground = "#313533"
background = "#e3e6e5"
cursor_bg = "#313533"
cursor_border = "#313533"
cursor_fg = "#e3e6e5"
selection_bg = "#939e9a"
selection_fg = "#313533"
split = "#4db290"
compose_cursor = "#998ed9"
scrollbar_thumb = "#79857f"

ansi = [
  "#e3e6e5",
  "#7872c2",
  "#49aa80",
  "#79857f",
  "#313533",
  "#998ed9",
  "#4db290",
  "#adb5b2",
]
brights = [
  "#939e9a",
  "#7872c2",
  "#49aa80",
  "#79857f",
  "#313533",
  "#998ed9",
  "#4db290",
  "#313533",
]

[colors.tab_bar]
inactive_tab_edge = "#cacecd"
background = "#e3e6e5"

[colors.tab_bar.active_tab]
fg_color = "#313533"
bg_color = "#d6dbd9"

[colors.tab_bar.inactive_tab]
fg_color = "#79857f"
bg_color = "#606a67"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d6dbd9"
bg_color = "#606a67"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#d6dbd9"
bg_color = "#e3e6e5"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#d6dbd9"
bg_color = "#e3e6e5"

[metadata]
aliases = []
author = "Black Atom Industries"
name = "Black Atom - Research"
