[colors]
foreground = "#ccb9b3"
background = "#242222"
cursor_bg = "#ef9e74"
cursor_border = "#ef9e74"
cursor_fg = "#242222"
selection_bg = "#7c6f64"
selection_fg = "#ccb9b3"
split = "#ef9e74"
compose_cursor = "#c4b2d1"
scrollbar_thumb = "#7c6f64"

ansi = [
  "#242222", # black
  "#c0603f", # dark_red
  "#7a895c", # dark_green
  "#ef9e74", # dark_yellow
  "#b6b3e5", # dark_blue
  "#d2acc3", # dark_magenta
  "#6a9b86", # dark_cyan
  "#ae9685", # light_gray
]

brights = [
  "#322e2b", # gray
  "#c57054", # red
  "#a6bc90", # green
  "#e0a66d", # yellow
  "#a6bbd9", # blue
  "#c4b2d1", # magenta
  "#7fb395", # cyan
  "#ccb9b3", # white
]

[colors.tab_bar]
inactive_tab_edge = "#1f1d1d"
background = "#242222"

[colors.tab_bar.active_tab]
fg_color = "#1f1d1d"
bg_color = "#a6bbd9"

[colors.tab_bar.inactive_tab]
fg_color = "#7c6f64"
bg_color = "#665c54"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a6bbd9"
bg_color = "#665c54"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#a6bbd9"
bg_color = "#242222"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#a6bbd9"
bg_color = "#242222"

[metadata]
aliases = []
author = "Black Atom Industries"
name = "Black Atom - Terra Fall Night"
