[colors]
foreground = "#313533"
background = "#d4dbd8"
cursor_bg = "#4db290"
cursor_border = "#4db290"
cursor_fg = "#d4dbd8"
selection_bg = "#939e9a"
selection_fg = "#313533"
split = "#4db290"
compose_cursor = "#998ed9"
scrollbar_thumb = "#79857f"

ansi = [
  "#313533", # black
  "#5d54ad", # dark_red
  "#4c8e62", # dark_green
  "#4a514f", # dark_yellow
  "#79857f", # dark_blue
  "#887bd3", # dark_magenta
  "#509583", # dark_cyan
  "#a2aba8", # light_gray
]

brights = [
  "#606a67", # gray
  "#7872c2", # red
  "#449f63", # green
  "#222325", # yellow
  "#606a67", # blue
  "#998ed9", # magenta
  "#4db290", # cyan
  "#d4dbd8", # white
]

[colors.tab_bar]
inactive_tab_edge = "#bcc3c0"
background = "#d4dbd8"

[colors.tab_bar.active_tab]
fg_color = "#bcc3c0"
bg_color = "#c8cfcd"

[colors.tab_bar.inactive_tab]
fg_color = "#79857f"
bg_color = "#606a67"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c8cfcd"
bg_color = "#606a67"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#c8cfcd"
bg_color = "#d4dbd8"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#c8cfcd"
bg_color = "#d4dbd8"

[metadata]
aliases = []
author = "Black Atom Industries"
name = "Black Atom - Medical"
