#!/bin/bash
# vim: set filetype=sh:

ORANGE='\033[0;33m'
NC='\033[0m' # No Color

function dotfiles() {
    /usr/bin/git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME" "$@"
}

# Update dotfiles
function push() {
    echo -e "${ORANGE}::: Pushing dotfiles...${NC}"
    dotfiles commit -a -m "Updates"
    dotfiles push
}

# Check the status of dotfiles
function status() {
    echo -e "${ORANGE}::: Checking status of dotfiles...${NC}"
    dotfiles status
}

# Add a file or folder
function add() {
    if [ -z "$2" ]; then
        echo "Please specify a file or folder to add."
        return 1
    fi
    echo -e "${ORANGE}::: Adding $2 to dotfiles...${NC}"
    dotfiles add "$2"
}

# Remove a file or folder
function remove() {
    if [ -z "$2" ]; then
        echo "Please specify a file or folder to remove."
        return 1
    fi
    echo -e "${ORANGE}::: Removing $2 from dotfiles...${NC}"
    dotfiles rm "$2"
}

# Pull changes from the remote repository
function pull() {
    echo -e "${ORANGE}::: Pulling changes from remote...${NC}"
    dotfiles pull
}

# Reset local changes and set to latest from remote
function reset() {
    echo -e "${ORANGE}::: Resetting to latest remote state...${NC}"
    dotfiles fetch --all
    dotfiles reset --hard origin/master
}

# List submodules
function list_submodules() {
    echo -e "${ORANGE}::: Listing submodules...${NC}"
    dotfiles submodule
}

# Add a submodule
function add_submodule() {
    local submodule_url=$1
    local submodule_path=$2
    echo -e "${ORANGE}::: Adding submodule $submodule_path...${NC}"
    dotfiles submodule add "$submodule_url" "$submodule_path"
    dotfiles add .
    dotfiles commit -m "Add submodule $submodule_path"
    dotfiles push
}

# Remove a submodule
function remove_submodule() {
    local submodule_path=$1
    echo -e "${ORANGE}::: Removing submodule $submodule_path...${NC}"
    dotfiles submodule deinit -f "$submodule_path"
    dotfiles rm --cached "$submodule_path"
    rm -rf "$HOME/.dotfiles/modules/$submodule_path"
    rm -rf "$submodule_path"
    dotfiles commit -m "Remove submodule $submodule_path"
    dotfiles push
}

case $1 in
"--push")
    push
    ;;
"--status")
    status
    ;;
"--add")
    add "$@"
    ;;
"--rm")
    remove "$@"
    ;;
"--pull")
    pull
    ;;
"--reset")
    reset
    ;;
"--submodules")
    list_submodules
    ;;
"--sync-submodules")
    sync_submodules
    ;;
"--add-submodule")
    add_submodule "$2" "$3"
    ;;
"--rm-submodule")
    remove_submodule "$2"
    ;;
*)
    echo "Unknown argument \"$1\""
    ;;
esac
