#!/usr/bin/env bash
function os_open {
  echo "$@"
  local uname
  uname="$(uname)"
  if [[ "$uname" == "Linux" ]]
  then
    xdg-open "$@"
  elif [[ "$uname" == Darwin ]]
  then 
    open -u "$@"
  else
    echo "Unable to detect OS."
    exit 1
  fi
}

# Opens the github page for the current git repository in your browser
# git@github.com:jasonneylon/dotfiles.git
# https://github.com/jasonneylon/dotfiles/
function get_git_url {
  giturl=$(git config --get remote.origin.url)
  if [ "${giturl}" == "" ]
  then
    echo "Not a git repository or no remote.origin.url set"
  exit 1;
  fi
  giturl=${giturl/\://}
  giturl=${giturl/git\@/https://}
  giturl=${giturl/\.git/\/}
  echo "${giturl}"
}

function main_branch {
  if git branch -a | grep -q " master$"
  then 
    echo "master"
  else
    echo "main"
  fi
}

function current_branch {
  git rev-parse --abbrev-ref HEAD
}

giturl="$(get_git_url)"

if [ "$#" -lt 1 ]
then
  os_open "${giturl}" && exit 0
fi

if [[ "$1" == "pr" ]]
then
  if [[ "${giturl}" == https://github.com/* ]]
  then
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request
    os_open "${giturl}compare/$(main_branch)...$(current_branch)?quick_pull=1"
  else
    # TODO: gitlab.com should be supported, because it is the BEST
    echo "This Git provider is currently not supported." 
    exit 1
  fi
fi

if [[ "$1" == "dcdpr" ]]
then
  branch="$(current_branch)"
  last_commit_msg="$(git show --no-patch --format=%s)"  
  last_commit_msg="$(echo "${last_commit_msg}" | jq -sRr @uri)"
  last_commit_msg="${last_commit_msg// /+}"
  # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request
  os_open "${giturl}compare/$(main_branch)...${branch}?quick_pull=1&title=${last_commit_msg}&assignees=$(git config user.name)"
fi
