#!/bin/bash
# vim: set filetype=sh:

# Define the repos directory
repos_path="$HOME/Documents/dev/repos"

select_repo() {
    # Let the user select a directory inside the repos directory and return the path to the selected directory
    find "$repos_path" -maxdepth 1 -type d -not -path "$repos_path" | fzf --prompt='Select a repository: '
}

# Open fzf in a tmux popup to select a git repository
selected_repo=$(select_repo)

# If a repo was selected
if [ -n "$selected_repo" ]; then
    # Parse the selected_repo string to get string after @
    session_name=$(echo "$selected_repo" | cut -d'@' -f2 | tr '.' '_')

    # Start a new tmux session with the selected repo as the cwd
    tmux new-session -d -s "$session_name" -c "$selected_repo"

    # Rename the first window "code"
    tmux rename-window -t "$session_name":1 "code"

    # Run "nvim ." in the first window
    tmux send-keys -t "$session_name":1 "nvim ." Enter

    # Create a new window with the same cwd
    tmux new-window -t "$session_name" -c "$selected_repo" -n "run"

    # Run "tmux_2x2_layout" in the second window
    tmux send-keys -t "$session_name":2 "tmux_2x2_layout" Enter

    # Display loading message in the center of the status bar
    tmux display-message -p -c "#{pane_current_path}" "Loading..."

    sleep 2

    # Switch to the new session
    tmux switch-client -t "$session_name"

    # Select the first window "code"
    tmux select-window -t "$session_name":1
else
    echo "No repository selected."
fi
