#!/opt/homebrew/bin/bash
# vim: set filetype=sh:

# Define the repos directory
repos_path="$HOME/Documents/dev/repos"

select_repo() {
    local IFS=$'\n' dirs names selected_name full_path
    # Use mapfile to read the full directory paths into an array
    mapfile -t dirs < <(find "$repos_path" -maxdepth 1 -type d -not -path "$repos_path" | sort)

    # Use mapfile to read the directory names into an array, converting full paths to basenames
    mapfile -t names < <(printf '%s\n' "${dirs[@]}" | xargs -I {} basename {} | sort)

    # Let the user select a directory name
    selected_name=$(printf '%s\n' "${names[@]}" | fzf --prompt='Select a repository: ')

    # Find the full path of the selected directory
    for dir in "${dirs[@]}"; do
        if [[ $(basename "$dir") == "$selected_name" ]]; then
            full_path="$dir"
            break
        fi
    done

    # Return the full path
    echo "$full_path"
}

# Open fzf in a tmux popup to select a git repository
selected_repo=$(select_repo)

# If a repo was selected
if [ -n "$selected_repo" ]; then
    # Parse the selected_repo string to get string after @
    session_name=$(echo "$selected_repo" | cut -d'@' -f2 | tr '.' '_')

    # Start a new tmux session with the selected repo as the cwd
    tmux new-session -d -s "$session_name" -c "$selected_repo"

    # Rename the first window "code"
    tmux rename-window -t "$session_name":1 "code"

    # Run "nvim ." in the first window
    tmux send-keys -t "$session_name":1 "nvim ." Enter

    # Create a new window with the same cwd
    tmux new-window -t "$session_name" -c "$selected_repo" -n "run"

    # Run "tmux_2x2_layout" in the second window
    tmux send-keys -t "$session_name":2 "tmux_2x2_layout" Enter

    # Display loading message in the center of the status bar
    tmux display-message -p -c "#{pane_current_path}" "Loading..."

    sleep 2

    # Switch to the new session
    tmux switch-client -t "$session_name"

    # Select the first window "code"
    tmux select-window -t "$session_name":1
else
    echo "No repository selected."
fi
