# rich colors: https://rich.readthedocs.io/en/stable/appendix/colors.html
# nerd fonts: https://www.nerdfonts.com/

main:
  body_dim: dim white
  body_highlight: blue
  header_dim: dim white
  header_highlight: blue

menu:
  icons:
    nested_close: 
    nested_open: ﱮ
    single_topic: 

  theme:
    style_editing: reverse red
    style_focused: reverse red
    style_unfocused: white

status_bar:
  theme:
    clock: reverse yellow
    date: reverse green
    insert: cyan
    message: purple1
    normal: blue
    search: magenta
    sort: green

  icons:
    calendar: 
    clock: 

todos:
  icons:
    due_date: 
    todo_completed: 
    todo_overdue: 
    todo_pending: 
    urgency: 

  theme:
    style_editing: bold cyan
    style_focused: bold grey85
    style_unfocused: bold grey50

keybindings:
  move_to_top: [g, home]
  move_to_bottom: [G, end]
  move_down: [j, down]
  shift_down: [J, shift+down]
  move_up: [k, up]
  shift_up: [K, shift+up]
  edit_node: i
  edit_date: d
  toggle_complete: c
  yank_todo: y
  toggle_expand: z
  toggle_expand_parent: Z
  remove_node: x
  add_sibling: a
  add_child: A
  spawn_sort_menu: ctrl+s
  start_search: /
  select_node: enter
  move_focus_to_menu: h
  show_help: "?"
  increase_urgency: ["+", "="]
  decrease_urgency: ["-", "_"]

welcome_message: |+
  JUST DO YOUR CHRORES ALREADY INSTEAD
  OF ORGANIZING SO YOU CAN PROCRASTINATE THEM

ascii_art: |+
  ██████╗  ██████╗  ██████╗ ██╗████████╗
      ██╔══██╗██╔═══██╗██╔═══██╗██║╚══██╔══╝
      ██║  ██║██║   ██║██║   ██║██║   ██║
      ██║  ██║██║   ██║██║   ██║██║   ██║
      ██████╔╝╚██████╔╝╚██████╔╝██║   ██║
      ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝   ╚═╝
